language: python
python:
  - "3.9"
os:
  - linux
git:
  depth: 1
env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/master_reader
  - PLATFORMIO_PROJECT_DIR=examples/master_writer
  - PLATFORMIO_PROJECT_DIR=examples/slave_receiver
  - PLATFORMIO_PROJECT_DIR=examples/slave_sender
  - PLATFORMIO_PROJECT_DIR=examples/DieTemperatureMeasurement
  - PLATFORMIO_PROJECT_DIR=examples/HeapMemoryMeasurement
  - PLATFORMIO_PROJECT_DIR=examples/SleepModeXMC1100
  - PLATFORMIO_PROJECT_DIR=examples/SleepModeXMC4700
  - PLATFORMIO_PROJECT_DIR=examples/StackMemoryMeasurement
  - PLATFORMIO_PROJECT_DIR=examples/ifx9201/MotorControl
  - PLATFORMIO_PROJECT_DIR=examples/rtc/AlarmRTC
  - PLATFORMIO_PROJECT_DIR=examples/rtc/HibernateRTCAlarm
  - PLATFORMIO_PROJECT_DIR=examples/rtc/SimpleRTC
  - PLATFORMIO_PROJECT_DIR=examples/spi/BarometricPressureSensor
  - PLATFORMIO_PROJECT_DIR=examples/spi/DigitalPotControl
  - PLATFORMIO_PROJECT_DIR=examples/ultrasonic/betterecho
  - PLATFORMIO_PROJECT_DIR=examples/ultrasonic/simple-echo
  - PLATFORMIO_PROJECT_DIR=examples/radar/doppler_speed

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR
